name: Continuous Integration

concurrency:
   group: ci-${{ github.event.number }}
   cancel-in-progress: true

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "31 1,12 * * *"

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: Shellcheck
    uses: nanlabs/devops-reference/.github/workflows/shellcheck.yml@main

  markdownlint:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    name: Markdownlint
    uses: nanlabs/devops-reference/.github/workflows/markdownlint.yml@main

  todo:
    if: github.event_name == 'push'
    name: TODO
    uses: nanlabs/devops-reference/.github/workflows/todo.yml@main

  update-readme:
    if: github.event_name == 'push'
    name: Update README
    uses: ./.github/workflows/generate-readme.yml

  pr-review:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    name: Pull Request Validation
    uses: nanlabs/devops-reference/.github/workflows/pr-review.yml@main
